arm64: fix the mm build error in mm/kfence/core.c
When I build kernel with ARCH=arm64, the building errors came out like
this:
  CC      mm/kfence/core.o
In file included from ../mm/kfence/core.c:21:
../arch/arm64/include/asm/kfence.h: In function ‘kfence_protect_page’:
../arch/arm64/include/asm/kfence.h:12:2: error: implicit declaration of
function ‘set_memory_valid’ [-Werror=implicit-function-declaration]
   12 |  set_memory_valid(addr, 1, !protect);
      |  ^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors

which introduced by commit d54febeba2ff ("kfence: use pt_regs to
generate stack trace on faults").

Signed-off-by: Hui Su <sh_def@163.com>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>